#!/bin/bash

# ============================================================
#  ANPR THESIS — Docker Tutorial + App Launcher
#  Run this every time:  bash start.sh
# ============================================================

clear

echo "╔══════════════════════════════════════════════════════════╗"
echo "║          DOCKER TUTORIAL — ANPR THESIS SYSTEM           ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  LESSON 1 — What is Docker?"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Docker packages your app + all its dependencies into a"
echo "  'container' — like a sealed box that runs the same way"
echo "  on any computer."
echo ""
echo "  Without Docker:"
echo "    Your PC:    python 3.10 ✓  postgres ✓  paddleocr ✓"
echo "    Others PC:  python 3.9  ✗  postgres ✗  paddleocr ✗  <- breaks"
echo ""
echo "  With Docker:"
echo "    Anyone just runs: docker compose up  ✓  Always works."
echo ""

read -p "  Press ENTER for next lesson..." _

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  LESSON 2 — Key Docker Concepts"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  IMAGE   = A blueprint (like a class in Python)."
echo "            Built once from a Dockerfile."
echo "            Example: your backend image."
echo ""
echo "  CONTAINER = A running instance of an image (like an object)."
echo "              You can start/stop/restart it."
echo "              Example: the running FastAPI server."
echo ""
echo "  VOLUME  = Persistent storage that survives container restarts."
echo "            Example: pgdata keeps your database even if"
echo "            the postgres container is deleted."
echo ""
echo "  NETWORK = Docker Compose auto-creates a private LAN so"
echo "            containers talk to each other by SERVICE NAME."
echo "            Example: backend connects to 'postgres:5432'"
echo "            NOT 'localhost:5432'."
echo ""

read -p "  Press ENTER for next lesson..." _

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  LESSON 3 — Your docker-compose.yml Explained"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  services:"
echo "    postgres:              <- Service 1: database"
echo "      image: postgres:16   <- Use official image, no build needed"
echo "      ports: 5432:5432     <- host:container port mapping"
echo "      volumes: pgdata      <- data persists between restarts"
echo ""
echo "    backend:               <- Service 2: your FastAPI app"
echo "      build: ./backend     <- Build from backend/Dockerfile"
echo "      ports: 8000:8000     <- FastAPI accessible on localhost:8000"
echo "      depends_on: postgres <- Postgres starts first"
echo "      environment:         <- Env vars injected into container"
echo "        DATABASE_URL: ...@postgres:5432...  <- note: 'postgres' not 'localhost'"
echo ""
echo "  volumes:"
echo "    pgdata:                <- Named volume for DB persistence"
echo ""

read -p "  Press ENTER for next lesson..." _

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  LESSON 4 — Your Dockerfile Explained (backend/Dockerfile)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  FROM python:3.10-slim      <- Start from official Python image"
echo "  RUN apt-get install ...    <- Install system libs (OpenCV, ffmpeg)"
echo "  WORKDIR /app               <- All commands run from /app inside container"
echo "  COPY requirements.txt .    <- Copy deps list first (for layer caching)"
echo "  RUN pip install -r ...     <- Install Python packages"
echo "  COPY . .                   <- Copy your actual code"
echo "  EXPOSE 8000                <- Document which port the app uses"
echo "  CMD [\"uvicorn\", ...]       <- Command that runs when container starts"
echo ""
echo "  WHY copy requirements.txt BEFORE the code?"
echo "  Docker caches each step. If you change only your .py files,"
echo "  Docker skips re-installing pip packages. Saves minutes."
echo ""

read -p "  Press ENTER for next lesson..." _

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  LESSON 5 — Commands You'll Use Every Day"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  START:"
echo "    docker compose up --build       <- build + start (use when code changed)"
echo "    docker compose up -d --build    <- same but runs in background"
echo ""
echo "  LOGS:"
echo "    docker compose logs -f          <- all services, live"
echo "    docker compose logs -f backend  <- backend only"
echo "    docker compose logs -f postgres <- database only"
echo ""
echo "  STOP:"
echo "    docker compose down             <- stop + remove containers"
echo "    docker compose down -v          <- also delete database volume (fresh DB)"
echo ""
echo "  DEBUG (get inside a container):"
echo "    docker compose exec backend bash    <- shell inside backend container"
echo "    docker compose exec postgres psql -U postgres thesis_db  <- postgres CLI"
echo ""
echo "  STATUS:"
echo "    docker compose ps    <- show running containers"
echo "    docker ps            <- all containers on your machine"
echo ""

read -p "  Press ENTER to start the app..." _

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  STARTING: ANPR Thesis System"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  PostgreSQL → localhost:5432"
echo "  FastAPI    → localhost:8000"
echo "  Dashboard  → localhost:3000 (run frontend separately)"
echo ""
echo "  Tip: Use Ctrl+C to stop."
echo ""

docker compose up --build
